#!/bin/sh
# $Id: test_update,v 1.9 2002/11/03 15:48:19 verthezp Exp $
# $Name: R0_90_0 $

builddir=`pwd`
if [ -z "$srcdir" ]
then
  srcdir=.
fi

test_program=updatetest
test_libs=$builddir/../gedcom/libgedcom.la

. $srcdir/src/test_prologue.sh
. $srcdir/src/test_bulk.sh
