#define yy_create_buffer gedcom_date__create_buffer
#define yy_delete_buffer gedcom_date__delete_buffer
#define yy_scan_buffer gedcom_date__scan_buffer
#define yy_scan_string gedcom_date__scan_string
#define yy_scan_bytes gedcom_date__scan_bytes
#define yy_flex_debug gedcom_date__flex_debug
#define yy_init_buffer gedcom_date__init_buffer
#define yy_flush_buffer gedcom_date__flush_buffer
#define yy_load_buffer_state gedcom_date__load_buffer_state
#define yy_switch_to_buffer gedcom_date__switch_to_buffer
#define yyin gedcom_date_in
#define yyleng gedcom_date_leng
#define yylex gedcom_date_lex
#define yyout gedcom_date_out
#define yyrestart gedcom_date_restart
#define yytext gedcom_date_text
#define yywrap gedcom_date_wrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
static yyconst short int yy_accept[337] =
    {   0,
        0,    0,   56,   56,   62,   60,    1,   61,   55,   58,
       59,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   56,
        1,   56,   55,   57,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,    1,   59,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    8,    0,    0,    0,   56,    1,

       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,    8,
       56,   56,   56,    0,    0,   40,   13,   34,   35,   10,
       12,   20,   24,    9,   11,    0,   14,    0,   30,   28,
       41,   15,   18,    0,    0,    0,    0,    0,   16,   37,
       17,   23,   22,   31,   19,   21,    0,    0,   27,   36,
       26,    0,    0,   25,   33,   38,    0,   39,   29,   32,
        0,   56,   56,   40,   13,   34,   35,   10,   12,   20,

       24,    9,   11,   56,   14,   56,   30,   28,   41,   15,
       18,   56,   56,   56,   56,   56,   16,   37,   17,   23,
       22,   31,   19,   21,   56,   56,   27,   36,   26,   56,
       56,   25,   33,   38,   56,   39,   29,   32,   56,    6,
        0,    0,    0,    0,   43,   54,   49,   44,    7,   53,
       48,   51,   45,   46,   50,   52,   42,   47,    6,   56,
       56,   56,   56,   43,   54,   49,   44,    7,   53,   48,
       51,   45,   46,   50,   52,   42,   47,    0,    0,    0,
        0,   56,   56,   56,   56,    0,    0,    0,    0,   56,
       56,   56,   56,    0,    0,    0,    0,   56,   56,   56,

       56,    0,    0,    0,    0,   56,   56,   56,   56,    0,
        0,    0,    0,   56,   56,   56,   56,    0,    0,    4,
        3,   56,   56,    4,    3,    0,    0,   56,   56,    5,
        0,    5,   56,    2,    2,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    1,    6,
        7,    1,    1,    1,    1,    1,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,    1,
        1,    1,    1,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
        1,   27,   28,   29,   30,   31,   32,    1,   33,   34,
        1,    1,    1,    1,    1,    1,   11,   12,   13,   14,

       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,    1,   27,   28,   29,   30,   31,   32,    1,
       33,   34,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[35] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[340] =
    {   0,
        0,    0,   34,    0,  498,  499,   67,  499,  499,  499,
      488,  491,   61,   55,   65,  480,   52,   73,  479,   59,
       67,  465,   83,   77,  479,   57,   86,   85,  476,    0,
      105,    0,    0,  499,    0,  481,  484,  107,   84,  101,
      473,   92,  100,  472,  101,  113,  458,  117,  111,  472,
       59,  120,  122,  469,  140,  474,  468,  450,  451,  121,
      450,  464,  450,  459,  125,  445,  452,  450,  454,  458,
      448,  440,  456,  442,  127,  439,  436,  437,  439,  134,
      440,  128,  433,  429,  428,  434,  428,  426,  444,  428,
      422,  428,  436,  416,  499,  431,  419,  423,    0,  158,

      437,  156,  414,  415,  137,  414,  428,  414,  423,  150,
      409,  416,  414,  418,  422,  412,  404,  420,  406,  148,
      403,  400,  401,  403,  147,  404,  141,  397,  393,  392,
      398,  392,  390,  408,  392,  386,  392,  400,  380,    0,
      395,  383,  387,  400,  165,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  386,  499,  382,  499,  499,
      499,  499,  499,  380,  383,  382,  391,  380,  499,  499,
      499,  499,  499,  499,  499,  499,  374,  376,  499,  499,
      499,  369,  376,  499,  499,  499,  363,  499,  499,  499,
      158,  181,  189,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,  364,    0,  360,    0,    0,    0,    0,
        0,  358,  359,  356,  364,  346,    0,    0,    0,    0,
        0,    0,    0,    0,  339,  339,    0,    0,    0,  330,
      340,    0,    0,    0,  323,    0,    0,    0,  166,  323,
       79,  166,  179,  167,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  201,  207,
      209,  215,  217,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  188,  211,  190,
      191,  225,  234,  236,  235,  205,  241,  223,  242,  252,
      253,  261,  262,  264,  257,  263,  243,  276,  277,  288,

      289,  213,  280,  265,  284,  302,  303,  308,  314,  312,
      304,  318,  294,  322,  324,  332,  334,  309,  335,  291,
      283,  344,  345,  350,  355,  275,  339,  363,  365,  256,
      180,  371,  373,  176,  381,  499,  391,  393,  396
    } ;

static yyconst short int yy_def[340] =
    {   0,
      336,    1,  336,    3,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  337,
      337,  337,  337,  336,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  336,  336,  338,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  337,  337,

      337,  339,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  338,  338,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  339,  339,  337,  337,  337,  337,  337,  337,  337,

      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  338,
      338,  338,  338,  338,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  339,  339,
      339,  339,  339,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  338,  338,  338,
      338,  339,  339,  339,  339,  338,  338,  338,  338,  339,
      339,  339,  339,  338,  338,  338,  338,  339,  339,  339,

      339,  338,  338,  338,  338,  339,  339,  339,  339,  338,
      338,  338,  338,  339,  339,  339,  339,  338,  338,  338,
      338,  339,  339,  339,  339,  338,  338,  339,  339,  338,
      338,  339,  339,  338,  339,    0,  336,  336,  336
    } ;

static yyconst short int yy_nxt[534] =
    {   0,
        6,    7,    8,    7,    6,    9,    6,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,    6,   20,   21,
       22,    6,   23,   24,   25,   26,    6,   27,   28,    6,
       29,    6,    6,    6,   30,   31,   32,   31,   30,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   30,   45,   46,   47,   30,   48,   49,   50,   51,
       30,   52,   53,   30,   54,   30,   30,   30,   55,   65,
       55,   58,   59,   71,   60,   67,   61,   79,   88,   72,
      133,   66,   77,   89,   62,  134,   63,   73,  240,   68,
       64,   78,   69,   82,   74,   84,   80,   83,  110,   75,

       90,   85,   93,   91,   86,  278,  100,   94,  100,   95,
      111,  112,   96,  116,  118,   97,   92,  103,  104,  117,
      105,  119,  106,  124,  122,  113,  120,  127,  114,  129,
      107,  128,  108,  123,  135,  130,  109,  136,  131,  138,
      154,   55,  125,   55,  139,  165,  140,  148,  149,  141,
      137,  166,  142,  155,  175,  172,  167,  173,   99,  100,
      176,  100,  144,  196,  197,  202,  213,  223,  220,  193,
      221,  257,  214,  224,  240,  240,  240,  215,  203,  276,
      241,  242,  243,   99,  244,  240,  258,  144,  240,  334,
      259,   99,  279,  280,  277,  144,  281,  240,  259,  240,

      240,  288,  286,   99,  260,  261,  262,  144,  263,   99,
      259,   99,  289,  144,  240,  144,  259,   99,  259,   99,
      240,  144,  240,  144,  259,  287,  259,   99,  294,  284,
      310,  144,  240,  282,  259,  283,   99,   99,   99,  290,
      144,  144,  144,  259,  259,  259,  285,  292,  291,  296,
      240,  240,  240,  305,   99,   99,  293,  295,  144,  144,
      297,  259,  259,   99,   99,  240,  240,  144,  144,  299,
      259,  259,  240,  240,  240,  298,  302,  304,   99,   99,
      301,  303,  144,  144,  330,  259,  259,  300,  306,  240,
       99,   99,  240,  240,  144,  144,  312,  259,  259,  309,

      240,  307,  308,  321,   99,   99,  311,  313,  144,  144,
       99,  259,  259,  240,  144,  318,   99,  259,  240,  314,
      144,  240,  319,  259,   99,  322,   99,  320,  144,  315,
      144,  259,  240,  259,   99,  326,   99,  317,  144,  316,
      144,  324,  323,  325,  240,  327,   99,   99,  240,  275,
      144,  144,   99,  259,  259,  329,  144,   99,  274,  259,
      273,  144,  331,  272,  259,   99,  271,   99,  270,  144,
      328,  144,  332,   99,  259,   99,  269,  144,  268,  144,
      259,  267,  335,   99,  266,  265,  264,  144,  333,  256,
      259,   99,   99,  144,  255,  144,  192,  192,  192,  254,

      253,  252,  251,  250,  249,  248,  247,  246,  245,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  222,  219,  218,  217,  216,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  201,
      200,  199,  198,  195,  194,  101,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      177,  174,  171,  170,  169,  168,  164,  163,  162,  161,
      160,  159,  158,  157,  156,  153,  152,  151,  150,  147,
      146,  145,   56,  143,  132,  126,  121,  115,  102,  101,
       98,   87,   81,   76,   70,   57,   56,  336,    5,  336,

      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336
    } ;

static yyconst short int yy_chk[534] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    7,   14,
        7,   13,   13,   17,   13,   15,   13,   21,   26,   17,
       51,   14,   20,   26,   13,   51,   13,   18,  241,   15,
       13,   20,   15,   23,   18,   24,   21,   23,   39,   18,

       27,   24,   28,   27,   24,  241,   31,   28,   31,   28,
       39,   40,   28,   42,   43,   28,   27,   38,   38,   42,
       38,   43,   38,   46,   45,   40,   43,   48,   40,   49,
       38,   48,   38,   45,   52,   49,   38,   52,   49,   53,
       65,   55,   46,   55,   53,   75,   53,   60,   60,   53,
       52,   75,   53,   65,   82,   80,   75,   80,  102,  100,
       82,  100,  102,  105,  105,  110,  120,  127,  125,  102,
      125,  191,  120,  127,  145,  242,  244,  120,  110,  239,
      145,  145,  145,  192,  145,  334,  191,  192,  243,  331,
      192,  193,  242,  243,  239,  193,  244,  278,  193,  280,

      281,  280,  278,  259,  193,  193,  193,  259,  193,  260,
      259,  261,  281,  260,  286,  261,  260,  262,  261,  263,
      279,  262,  302,  263,  262,  279,  263,  282,  286,  262,
      302,  282,  288,  260,  282,  261,  283,  285,  284,  282,
      283,  285,  284,  283,  285,  284,  263,  284,  283,  288,
      287,  289,  297,  297,  290,  291,  285,  287,  290,  291,
      289,  290,  291,  292,  293,  330,  295,  292,  293,  291,
      292,  293,  296,  294,  304,  290,  294,  296,  298,  299,
      293,  295,  298,  299,  326,  298,  299,  292,  298,  303,
      300,  301,  321,  305,  300,  301,  304,  300,  301,  301,

      320,  299,  300,  313,  306,  307,  303,  305,  306,  307,
      308,  306,  307,  311,  308,  310,  309,  308,  318,  306,
      309,  310,  311,  309,  314,  314,  315,  312,  314,  307,
      315,  314,  240,  315,  316,  318,  317,  309,  316,  308,
      317,  316,  315,  317,  319,  319,  322,  323,  327,  235,
      322,  323,  324,  322,  323,  323,  324,  325,  231,  324,
      230,  325,  327,  226,  325,  328,  225,  329,  216,  328,
      322,  329,  328,  332,  329,  333,  215,  332,  214,  333,
      332,  213,  333,  335,  212,  206,  204,  335,  329,  187,
      335,  337,  337,  338,  183,  338,  339,  339,  339,  182,

      178,  177,  168,  167,  166,  165,  164,  158,  156,  144,
      143,  142,  141,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  129,  128,  126,  124,  123,  122,  121,
      119,  118,  117,  116,  115,  114,  113,  112,  111,  109,
      108,  107,  106,  104,  103,  101,   98,   97,   96,   94,
       93,   92,   91,   90,   89,   88,   87,   86,   85,   84,
       83,   81,   79,   78,   77,   76,   74,   73,   72,   71,
       70,   69,   68,   67,   66,   64,   63,   62,   61,   59,
       58,   57,   56,   54,   50,   47,   44,   41,   37,   36,
       29,   25,   22,   19,   16,   12,   11,    5,  336,  336,

      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gedcom_date.lex"
#define INITIAL 0
/* Lexer for Gedcom dates
   Copyright (C) 2001 The Genes Development Team
   This file is part of the Gedcom parser library.
   Contributed by Peter Verthez <Peter.Verthez@advalvas.be>, 2001.

   The Gedcom parser library is free software; you can redistribute it
   and/or modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The Gedcom parser library is distributed in the hope that it will be
   useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the Gedcom parser library; if not, write to the
   Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
   02111-1307 USA.  */
/* $Id: gedcom_date.lex,v 1.5 2002/12/21 16:53:17 verthezp Exp $ */
/* $Name: R0_90_0 $ */
#line 25 "gedcom_date.lex"
#include "date.h"
#include "gedcom_date.tabgen.h"
  
#define YY_NO_UNPUT

static char buf[MAX_DATE_TOKEN][MAX_PHRASE_LEN+1];
static int token_nr = 0; 
#define PHRASE 1

#line 639 "lex.gedcom_date_.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 37 "gedcom_date.lex"




#define SIMPLE_RETURN(TOKEN) \
  { if (token_nr >= MAX_DATE_TOKEN) { \
      gedcom_date_error(_("Date token stack overflow")); \
      return BADTOKEN; \
    } \
    memset(buf[token_nr], 0, MAX_PHRASE_LEN+1); \
    strncpy(buf[token_nr], yytext, yyleng); \
    gedcom_date_lval.string = buf[token_nr++]; \
    return TOKEN; \
  }

#define ACTION_UNEXPECTED \
  { gedcom_date_error(_("Unexpected input")); \
    return BADTOKEN; \
  }

#define UNKNOWN_CALENDAR_TYPE \
  { gedcom_date_error(_("Unknown calendar type")); \
    return BADTOKEN; \
  }


#line 817 "lex.gedcom_date_.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 337 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 499 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "gedcom_date.lex"
/* ignore whitespace between tokens */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 65 "gedcom_date.lex"
SIMPLE_RETURN(ESC_DATE_GREG)
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 66 "gedcom_date.lex"
SIMPLE_RETURN(ESC_DATE_JULN)
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 67 "gedcom_date.lex"
SIMPLE_RETURN(ESC_DATE_HEBR)
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 68 "gedcom_date.lex"
SIMPLE_RETURN(ESC_DATE_FREN)
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 69 "gedcom_date.lex"
UNKNOWN_CALENDAR_TYPE
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 71 "gedcom_date.lex"
SIMPLE_RETURN(MOD_FROM)
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 72 "gedcom_date.lex"
SIMPLE_RETURN(MOD_TO)  
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 73 "gedcom_date.lex"
SIMPLE_RETURN(MOD_BEF) 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 74 "gedcom_date.lex"
SIMPLE_RETURN(MOD_AFT) 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 75 "gedcom_date.lex"
SIMPLE_RETURN(MOD_BET) 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "gedcom_date.lex"
SIMPLE_RETURN(MOD_AND) 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 77 "gedcom_date.lex"
SIMPLE_RETURN(MOD_ABT) 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "gedcom_date.lex"
SIMPLE_RETURN(MOD_CAL) 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 79 "gedcom_date.lex"
SIMPLE_RETURN(MOD_EST) 
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 80 "gedcom_date.lex"
SIMPLE_RETURN(MOD_INT)
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 82 "gedcom_date.lex"
SIMPLE_RETURN(MON_JAN) 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 83 "gedcom_date.lex"
SIMPLE_RETURN(MON_FEB) 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 84 "gedcom_date.lex"
SIMPLE_RETURN(MON_MAR) 
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 85 "gedcom_date.lex"
SIMPLE_RETURN(MON_APR) 
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 86 "gedcom_date.lex"
SIMPLE_RETURN(MON_MAY) 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 87 "gedcom_date.lex"
SIMPLE_RETURN(MON_JUN) 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 88 "gedcom_date.lex"
SIMPLE_RETURN(MON_JUL) 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 89 "gedcom_date.lex"
SIMPLE_RETURN(MON_AUG) 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 90 "gedcom_date.lex"
SIMPLE_RETURN(MON_SEP) 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 91 "gedcom_date.lex"
SIMPLE_RETURN(MON_OCT) 
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 92 "gedcom_date.lex"
SIMPLE_RETURN(MON_NOV) 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 93 "gedcom_date.lex"
SIMPLE_RETURN(MON_DEC) 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 94 "gedcom_date.lex"
SIMPLE_RETURN(MON_TSH) 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 95 "gedcom_date.lex"
SIMPLE_RETURN(MON_CSH) 
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 96 "gedcom_date.lex"
SIMPLE_RETURN(MON_KSL) 
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 97 "gedcom_date.lex"
SIMPLE_RETURN(MON_TVT) 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 98 "gedcom_date.lex"
SIMPLE_RETURN(MON_SHV) 
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 99 "gedcom_date.lex"
SIMPLE_RETURN(MON_ADR) 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 100 "gedcom_date.lex"
SIMPLE_RETURN(MON_ADS) 
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 101 "gedcom_date.lex"
SIMPLE_RETURN(MON_NSN) 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 102 "gedcom_date.lex"
SIMPLE_RETURN(MON_IYR) 
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 103 "gedcom_date.lex"
SIMPLE_RETURN(MON_SVN) 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 104 "gedcom_date.lex"
SIMPLE_RETURN(MON_TMZ) 
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 105 "gedcom_date.lex"
SIMPLE_RETURN(MON_AAV) 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 106 "gedcom_date.lex"
SIMPLE_RETURN(MON_ELL) 
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 107 "gedcom_date.lex"
SIMPLE_RETURN(MON_VEND)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 108 "gedcom_date.lex"
SIMPLE_RETURN(MON_BRUM)
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 109 "gedcom_date.lex"
SIMPLE_RETURN(MON_FRIM)
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 110 "gedcom_date.lex"
SIMPLE_RETURN(MON_NIVO)
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 111 "gedcom_date.lex"
SIMPLE_RETURN(MON_PLUV)
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 112 "gedcom_date.lex"
SIMPLE_RETURN(MON_VENT)
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 113 "gedcom_date.lex"
SIMPLE_RETURN(MON_GERM)
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 114 "gedcom_date.lex"
SIMPLE_RETURN(MON_FLOR)
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 115 "gedcom_date.lex"
SIMPLE_RETURN(MON_PRAI)
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 116 "gedcom_date.lex"
SIMPLE_RETURN(MON_MESS)
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 117 "gedcom_date.lex"
SIMPLE_RETURN(MON_THER)
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 118 "gedcom_date.lex"
SIMPLE_RETURN(MON_FRUC)
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 119 "gedcom_date.lex"
SIMPLE_RETURN(MON_COMP)
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 121 "gedcom_date.lex"
{ BEGIN(PHRASE);
                  SIMPLE_RETURN(OPEN); 
                }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 124 "gedcom_date.lex"
SIMPLE_RETURN(TEXT);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 125 "gedcom_date.lex"
{ BEGIN(INITIAL); 
                  SIMPLE_RETURN(CLOSE);
                }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 129 "gedcom_date.lex"
SIMPLE_RETURN(SLASH)
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 130 "gedcom_date.lex"
SIMPLE_RETURN(NUMBER)
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 132 "gedcom_date.lex"
ACTION_UNEXPECTED
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 134 "gedcom_date.lex"
ECHO;
	YY_BREAK
#line 1209 "lex.gedcom_date_.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PHRASE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 337 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 337 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 336);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 134 "gedcom_date.lex"


int get_date_token(const char* str)
{
  int token;
  YY_BUFFER_STATE buffer;

  token_nr = 0;
  yy_delete_buffer(YY_CURRENT_BUFFER);
  buffer = yy_scan_string(str);
  token = yylex();
  yy_delete_buffer(buffer);
  return token;
}

int get_year_tokens(const char* str, char** year1, char** year2)
{
  int token;
  int num_tokens = 0;
  YY_BUFFER_STATE buffer;

  token_nr = 0;
  yy_delete_buffer(YY_CURRENT_BUFFER);
  buffer = yy_scan_string(str);

  token = yylex();
  switch (token) {
    case NUMBER: {
      *year1 = buf[token_nr - 1];
      token  = yylex();
      switch (token) {
	case SLASH: {
	  token = yylex();
	  switch (token) {
	    case NUMBER:
	      *year2 = buf[token_nr - 1];
	      num_tokens = 2; break;
	    default:
	      num_tokens = 0;
	  }
	  break;
	}
	case 0:   num_tokens = 1; break;
	default:  num_tokens = 0;
      }
      break;
    }
    case 0:   num_tokens = 0; break;
    default:  num_tokens = 0;
  }
  yy_delete_buffer(buffer);
  return num_tokens;
}

int yywrap()
{
  return 1;
}

static YY_BUFFER_STATE hndl;

void init_gedcom_date_lex(const char* string)
{
  token_nr = 0;
  hndl = yy_scan_string(string);
}

void close_gedcom_date_lex()
{
  yy_delete_buffer(hndl);
}
