#!/bin/sh
# $Id: test_updategom,v 1.1 2002/11/22 21:28:55 verthezp Exp $
# $Name: R0_90_0 $

builddir=`pwd`
if [ -z "$srcdir" ]
then
  srcdir=.
fi

test_program=updategomtest
test_libs="$builddir/../gedcom/libgedcom.la $builddir/../gom/libgedcom_gom.la"

. $srcdir/src/test_prologue.sh
. $srcdir/src/test_bulk.sh
