#!/bin/sh
# $Id: test_gom,v 1.11 2002/11/03 15:48:19 verthezp Exp $
# $Name: R0_90_0 $

builddir=`pwd`
if [ -z "$srcdir" ]
then
  srcdir=.
fi

. $srcdir/src/test_prologue.sh

file=$1

if [ -z "$srcdir" ]
then
  testfile=$file
else
  case $file in
    ./*) testfile=$file ;;
    *)   testfile=$srcdir/input/$file ;;
  esac
fi

test_program=gomtest
test_libs="$builddir/../gedcom/libgedcom.la $builddir/../gom/libgedcom_gom.la"
test_args=$testfile

. $srcdir/src/test_bulk.sh
