#define yy_create_buffer gedcom_hilo__create_buffer
#define yy_delete_buffer gedcom_hilo__delete_buffer
#define yy_scan_buffer gedcom_hilo__scan_buffer
#define yy_scan_string gedcom_hilo__scan_string
#define yy_scan_bytes gedcom_hilo__scan_bytes
#define yy_flex_debug gedcom_hilo__flex_debug
#define yy_init_buffer gedcom_hilo__init_buffer
#define yy_flush_buffer gedcom_hilo__flush_buffer
#define yy_load_buffer_state gedcom_hilo__load_buffer_state
#define yy_switch_to_buffer gedcom_hilo__switch_to_buffer
#define yyin gedcom_hilo_in
#define yyleng gedcom_hilo_leng
#define yylex gedcom_hilo_lex
#define yyout gedcom_hilo_out
#define yyrestart gedcom_hilo_restart
#define yytext gedcom_hilo_text
#define yywrap gedcom_hilo_wrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 142
#define YY_END_OF_BUFFER 143
static yyconst short int yy_acclist[508] =
    {   0,
        1,    1,  143,  141,  142,  142,  141,  142,  141,  142,
      141,  142,  135,    1,  140,  138,  138,    1,  134,  135,
        3,  135,    3,  135,  139,  140,  134,  133,  135,  133,
      135,  133,  135,  133,  135,  133,  135,  133,  135,  133,
      135,  133,  135,  133,  135,  133,  135,  133,  135,  133,
      135,  133,  135,  133,  135,  133,  135,  133,  135,  133,
      135,  133,  135,  133,  135,  133,  135,  133,  135,    1,
      138,    2,    3,    3,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,

      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  137,  133,  133,  133,  133,    9,  133,
       10,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,   33,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,   50,  133,  133,  133,  133,  133,  133,  133,

       58,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,   86,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  110,  133,  111,  133,  133,  113,  133,  133,
      133,  133,  118,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,16520,    4,  133,    5,
      133,    8,  133,    6,  133,    7,  133,   11,  133,   12,
      133,   13,  133,   14,  133,   15,  133,   16,  133,   17,
      133,   18,  133,   19,  133,   20,  133,   21,  133,   22,

      133,   23,  133,   24,  133,   25,  133,   26,  133,   27,
      133,   28,  133,   29,  133,   30,  133,   31,  133,   32,
      133,   34,  133,   35,  133,   36,  133,   37,  133,   38,
      133,   39,  133,   40,  133,   41,  133,   42,  133,   43,
      133,   44,  133,   45,  133,   46,  133,   47,  133,   48,
      133,   49,  133,   51,  133,   52,  133,   53,  133,   54,
      133,   55,  133,   56,  133,   57,  133,   59,  133,   60,
      133,   61,  133,   62,  133,   63,  133,   64,  133,   65,
      133,   66,  133,   67,  133,   68,  133,   69,  133,   70,
      133,   71,  133,   72,  133,   73,  133,   74,  133,   75,

      133,   76,  133,   77,  133,   78,  133,   79,  133,   80,
      133,   81,  133,   82,  133,   83,  133,   84,  133,   85,
      133,   87,  133,   88,  133,   89,  133,   90,  133,   91,
      133,   92,  133,   93,  133,   94,  133,   95,  133,   96,
      133,   97,  133,   98,  133,   99,  133,  100,  133,  101,
      133,  102,  133,  103,  133,  104,  133,  105,  133,  106,
      133,  107,  133,  108,  133,  109,  133,  112,  133,  114,
      133,  115,  133,  116,  133,  117,  133,  119,  133,  120,
      133,  121,  133,  122,  133,  123,  133,  124,  133,  125,
      133,  126,  133,  127,  133,  128,  133,  129,  133,  130,

      133,  131,  133,  132,  133, 8328, 8328
    } ;

static yyconst short int yy_accept[572] =
    {   0,
        1,    2,    3,    3,    3,    3,    3,    4,    6,    7,
        9,   11,   13,   14,   16,   17,   18,   20,   21,   23,
       25,   26,   27,   28,   30,   32,   34,   36,   38,   40,
       42,   44,   46,   48,   50,   52,   54,   56,   58,   60,
       62,   64,   66,   68,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   71,   72,   74,   75,   75,   75,   75,
       76,   77,   78,   79,   80,   81,   82,   83,   84,   85,
       86,   87,   88,   89,   90,   91,   92,   93,   94,   95,

       96,   97,   98,   99,  100,  101,  102,  103,  104,  105,
      106,  107,  108,  109,  110,  111,  112,  113,  114,  115,
      116,  117,  118,  119,  120,  121,  122,  123,  124,  125,
      126,  127,  128,  129,  130,  131,  132,  133,  134,  135,
      136,  137,  138,  139,  140,  141,  142,  143,  144,  145,
      146,  147,  148,  149,  150,  151,  152,  153,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,

      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  155,  156,  157,  158,
      159,  161,  163,  164,  165,  166,  167,  168,  169,  170,
      171,  172,  173,  174,  175,  176,  177,  178,  179,  180,
      181,  182,  184,  185,  186,  187,  188,  189,  190,  191,
      192,  193,  195,  196,  197,  198,  199,  200,  201,  203,
      204,  205,  206,  207,  208,  209,  210,  211,  212,  213,

      214,  215,  216,  217,  218,  219,  220,  221,  222,  224,
      225,  226,  227,  228,  229,  230,  231,  232,  233,  234,
      235,  236,  237,  238,  239,  240,  241,  242,  243,  245,
      247,  248,  250,  251,  252,  253,  255,  256,  257,  258,
      259,  260,  261,  262,  263,  264,  265,  266,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,

      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  268,  270,  272,  274,
      276,  278,  280,  282,  284,  286,  288,  290,  292,  294,
      296,  298,  300,  302,  304,  306,  308,  310,  312,  314,
      316,  318,  320,  322,  324,  326,  328,  330,  332,  334,
      336,  338,  340,  342,  344,  346,  348,  350,  352,  354,
      356,  358,  360,  362,  364,  366,  368,  370,  372,  374,

      376,  378,  380,  382,  384,  386,  388,  390,  392,  394,
      396,  398,  400,  402,  404,  406,  408,  410,  412,  414,
      416,  418,  420,  422,  424,  426,  428,  430,  432,  434,
      436,  438,  440,  442,  444,  446,  448,  450,  452,  454,
      456,  458,  460,  462,  464,  466,  468,  470,  472,  474,
      476,  478,  480,  482,  484,  486,  488,  490,  492,  494,
      496,  498,  500,  502,  504,  506,  506,  506,  507,  508,
      508
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    6,    7,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    8,    9,   10,
       11,   11,   11,   11,   11,   11,   11,    6,    6,    6,
        6,    6,    6,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
        6,    6,    6,    6,   38,    6,   38,   38,   38,   38,

       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,    6,    6,    6,    6,    1,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,

        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6
    } ;

static yyconst int yy_meta[40] =
    {   0,
        1,    2,    2,    2,    3,    3,    4,    5,    5,    5,
        5,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    1
    } ;

static yyconst short int yy_base[585] =
    {   0,
        0,    1,    2,    3,    4,    5,  794,    0,    0,   43,
       54,   65,  795,  754,  753,  752,  751,  795,  750,  749,
      748,  747,  746,  745,  744,  743,  742,  741,  740,  739,
      738,  737,  736,  735,  734,  733,  732,  731,  730,  729,
      728,  727,  726,  725,    7,  759,  759,    5,    9,   14,
       20,    0,   90,   94,  115,  109,  118,   98,  103,   17,
       11,   15,   16,  140,  124,  159,  728,  139,  176,  157,
      743,  738,  719,  795,  718,  717,  716,  715,  714,  713,
      712,  711,  710,  709,  708,  707,  706,  705,  704,  703,
      702,  701,  700,  699,  698,  697,  696,  695,  694,  693,

      692,  691,  690,  689,  688,  687,  686,  685,  684,  683,
      682,  681,  680,  679,  678,  677,  676,  675,  674,  673,
      672,  671,  670,  669,  668,  667,  666,  665,  664,  663,
      662,  661,  660,  659,  658,  657,  656,  655,  654,  653,
      652,  651,  650,  649,  648,  647,  646,  645,  644,  643,
      642,  641,  640,  639,  638,  637,  636,  635,    0,  125,
        0,  152,  659,  132,  646,  124,  650,  136,  639,  637,
       33,  638,  146,  637,  151,  640,  167,  633,  184,  647,
      633,  630,  164,  627,  645,  626,  637,   19,  640,  631,
      628,  630,  623,  636,  617,  637,  636,  617,  621,  621,

      629,  618,  624,  612,  625,   80,  620,  624,  608,  605,
      618,  617,  612,  618,  616,  612,  614,  602,  615,  596,
      599,  611,  611,  187,  597,  596,  597,  584,  600,  585,
      599,  590,  602,  171,  145,   85,  590,  585,  582,  172,
      572,  571,  570,  569,  568,  795,  567,  566,  565,  564,
      563,  562,  561,  560,  559,  558,  557,  556,  555,  554,
      553,  552,  551,  550,  549,  548,  547,  546,  545,  544,
      543,  542,  541,  540,  539,  538,  537,  536,  535,  534,
      533,  532,  531,  530,  529,  528,  527,  526,  525,  524,
      523,  522,  521,  520,  519,  518,  517,  516,  515,  514,

      513,  512,  511,  510,  509,  508,  507,  506,  505,  504,
      503,  502,  501,  500,  499,  498,  497,  496,  495,  494,
      493,  492,  491,  490,  489,  488,  487,  486,  485,  484,
      483,  482,  481,  480,  479,  478,  477,  476,  475,  474,
      473,  472,  471,  470,  469,  468,  467,  466,  210,  492,
      473,  472,  473,   21,  485,  486,  181,  474,  470,  476,
      196,  470,  469,  461,  461,  477,  469,  463,  456,  456,
      455,  187,  461,  471,  446,  208,  452,  453,  455,  442,
      211,  446,  210,  459,  446,  460,  455,  449,  459,  445,
      212,  445,  452,  443,  452,  440,  449,  448,  449,  435,

      440,  439,  440,  445,  220,  436,  439,  208,  434,  431,
      436,  416,  415,  433,  416,  212,  431,  426,  420,  430,
      412,  225,  419,  405,  415,  178,  413,  226,  418,  421,
      230,  407,  400,  231,  211,  409,  406,  401,  415,  407,
      400,  412,  397,  410,  402,  386,  385,  384,  383,  382,
      381,  380,  379,  378,  377,  376,  375,  374,  373,  372,
      371,  370,  369,  368,  367,  366,  365,  364,  363,  362,
      361,  360,  359,  358,  357,  356,  355,  354,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  344,  343,  342,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,

      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  280,  223,  221,  220,  219,  218,  217,  215,  207,
      167,  110,  107,   90,   26,    0,  243,  795,  795,  795,
      263,  268,  272,  274,   57,  279,  284,  289,  292,  297,
      300,  305,  310,  313
    } ;

static yyconst short int yy_def[585] =
    {   0,
      571,  571,  571,  571,  571,  571,  570,  572,  572,  573,
      573,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  574,
      570,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  570,  570,  570,  570,  576,  577,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,

      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  578,  579,
      580,  581,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,

      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      576,  576,  570,  577,  577,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,

      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  579,  570,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,

      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  582,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,

      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  583,  584,  570,  570,    0,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570
    } ;

static yyconst short int yy_nxt[835] =
    {   0,
      570,  570,    9,    9,    9,    9,    9,    9,   73,   15,
       16,   73,   75,   75,   75,   75,   76,   76,   76,   76,
       77,   79,   15,   16,   79,   18,  117,  120,  122,  450,
      451,  121,  123,  115,  286,  118,  119,  287,   10,   10,
       11,   11,   12,   12,   14,   15,   16,   17,   13,  116,
       19,   20,   20,   20,   21,   22,   15,   16,   23,   13,
      259,   80,  260,  261,   52,   21,   22,   15,   16,   23,
       13,   18,   24,   24,   24,   24,   21,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   24,   24,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   24,   43,   44,

       24,   24,   24,   81,  305,   82,   89,   83,   84,  342,
      108,  306,  109,   85,   90,   86,  343,   91,  110,  112,
       87,  100,   88,  113,  111,  101,   92,   93,   52,  102,
      241,   94,  114,  104,   95,   96,  243,  131,  132,  103,
      252,   97,  105,  106,   98,   52,   99,  248,   52,  253,
      255,  107,  124,  133,  125,  142,  143,  244,  249,  144,
      126,  250,  263,  246,  127,  145,  128,  129,  256,  340,
      130,  134,  264,  153,  266,  135,  280,  154,  136,  270,
      341,  267,  137,  268,  338,  138,  155,  271,  139,  347,
      541,  140,  146,  156,  281,  348,  272,  454,  542,  147,

      339,  455,  148,  149,  324,   52,  150,  151,  152,  274,
      325,  275,  471,  276,  326,  241,  472,  327,  328,  459,
      460,  446,  476,  484,  487,  477,  497,  485,  520,  498,
      488,  478,  529,  513,  514,  554,  555,  530,  536,  479,
      521,  489,  499,  515,  548,   52,  544,  552,  568,  516,
      517,  545,  537,   52,  242,   52,   52,   52,   52,   52,
      549,   52,  553,    8,    8,    8,    8,    8,   13,   13,
       13,   13,   13,   18,   18,   18,   18,   78,   78,  159,
      159,  159,  159,  159,  161,  161,  161,  161,  161,  241,
      241,  241,  241,  241,  242,  242,  242,  244,  244,  244,

      244,  244,  245,  245,  245,  566,  566,  566,  566,  566,
      568,  568,  568,  568,  568,  569,  569,  569,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,

       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  567,  565,  564,  563,  562,  561,
      560,  559,  558,  557,  556,  551,  550,  547,  546,  543,
      540,  539,  538,  535,  534,  533,  532,  531,  528,  527,
      526,  525,  524,  523,  522,  519,  518,  512,  511,  510,
      509,  508,  507,  506,  505,  504,  503,  502,  501,  500,
      496,  495,  494,  493,  492,  491,  490,  486,  483,  482,
      481,  480,  475,  474,  473,  470,  469,  468,  467,  466,
      465,  464,  463,  462,  461,  458,  457,  456,  453,  452,

      449,  448,  447,  242,  445,  444,  443,  442,  441,  440,
      439,  438,  437,  436,  435,  434,   52,  433,  432,  431,
       52,  430,   52,   52,  429,  428,  427,  426,  425,  424,
      423,  422,  421,  420,  419,  418,  417,  416,  415,  414,
      413,  412,  411,   52,  410,  409,  408,  407,  406,  405,
      404,  403,  402,  401,  400,  399,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  385,
      384,  383,  382,  381,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  363,  362,  361,  360,  359,  358,  357,  356,  355,

       52,   52,  354,  353,  352,  351,  162,  162,  350,  349,
      349,  346,  345,  344,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  323,  322,  321,  320,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  285,  284,  283,
      282,  279,  278,  277,  273,  269,  265,  262,  258,  257,
      254,  251,  247,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,

      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,   52,   51,  162,  160,   49,   48,   45,  158,  157,
      141,   74,   74,   72,   71,   70,   69,   68,   67,   66,
       65,   64,   63,   62,   61,   60,   59,   58,   57,   56,
       55,   54,   53,   52,   51,   51,   50,   49,   48,   45,
       47,   46,   45,  570,    7,  570,  570,  570,  570,  570,

      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570
    } ;

static yyconst short int yy_chk[835] =
    {   0,
        0,    0,    1,    2,    3,    4,    5,    6,   45,   45,
       45,   45,   48,   48,   48,   48,   49,   49,   49,   49,
       50,   51,   51,   51,   51,   50,   61,   62,   63,  354,
      354,   62,   63,   60,  188,   61,   61,  188,    1,    2,
        3,    4,    5,    6,   10,   10,   10,   10,   10,   60,
       10,   10,   10,   10,   10,   11,   11,   11,   11,   11,
      171,  575,  171,  171,  565,   11,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,

       12,   12,   12,   53,  206,   53,   54,   53,   53,  236,
       58,  206,   58,   53,   54,   53,  236,   54,   58,   59,
       53,   56,   53,   59,   58,   56,   54,   55,  564,   56,
      160,   55,   59,   57,   55,   55,  160,   65,   65,   56,
      166,   55,   57,   57,   55,  563,   55,  164,  562,  166,
      168,   57,   64,   65,   64,   68,   68,  162,  164,   68,
       64,  164,  173,  162,   64,   68,   64,   64,  168,  235,
       64,   66,  173,   70,  175,   66,  183,   70,   66,  177,
      235,  175,   66,  175,  234,   66,   70,  177,   66,  240,
      426,   66,   69,   70,  183,  240,  177,  357,  426,   69,

      234,  357,   69,   69,  224,  561,   69,   69,   69,  179,
      224,  179,  372,  179,  224,  349,  372,  224,  224,  361,
      361,  349,  376,  381,  383,  376,  391,  381,  408,  391,
      383,  376,  416,  405,  405,  435,  435,  416,  422,  376,
      408,  383,  391,  405,  431,  560,  428,  434,  567,  405,
      405,  428,  422,  559,  567,  558,  557,  556,  555,  554,
      431,  553,  434,  571,  571,  571,  571,  571,  572,  572,
      572,  572,  572,  573,  573,  573,  573,  574,  574,  576,
      576,  576,  576,  576,  577,  577,  577,  577,  577,  578,
      578,  578,  578,  578,  579,  579,  579,  580,  580,  580,

      580,  580,  581,  581,  581,  582,  582,  582,  582,  582,
      583,  583,  583,  583,  583,  584,  584,  584,  552,  551,
      550,  549,  548,  547,  546,  545,  544,  543,  542,  541,
      540,  539,  538,  537,  536,  535,  534,  533,  532,  531,
      530,  529,  528,  527,  526,  525,  524,  523,  522,  521,
      520,  519,  518,  517,  516,  515,  514,  513,  512,  511,
      510,  509,  508,  507,  506,  505,  504,  503,  502,  501,
      500,  499,  498,  497,  496,  495,  494,  493,  492,  491,
      490,  489,  488,  487,  486,  485,  484,  483,  482,  481,
      480,  479,  478,  477,  476,  475,  474,  473,  472,  471,

      470,  469,  468,  467,  466,  465,  464,  463,  462,  461,
      460,  459,  458,  457,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  439,  438,  437,  436,  433,  432,  430,  429,  427,
      425,  424,  423,  421,  420,  419,  418,  417,  415,  414,
      413,  412,  411,  410,  409,  407,  406,  404,  403,  402,
      401,  400,  399,  398,  397,  396,  395,  394,  393,  392,
      390,  389,  388,  387,  386,  385,  384,  382,  380,  379,
      378,  377,  375,  374,  373,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  360,  359,  358,  356,  355,

      353,  352,  351,  350,  348,  347,  346,  345,  344,  343,
      342,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,

      252,  251,  250,  249,  248,  247,  245,  244,  243,  242,
      241,  239,  238,  237,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  187,  186,  185,
      184,  182,  181,  180,  178,  176,  174,  172,  170,  169,
      167,  165,  163,  158,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  146,  145,  144,  143,  142,
      141,  140,  139,  138,  137,  136,  135,  134,  133,  132,

      131,  130,  129,  128,  127,  126,  125,  124,  123,  122,
      121,  120,  119,  118,  117,  116,  115,  114,  113,  112,
      111,  110,  109,  108,  107,  106,  105,  104,  103,  102,
      101,  100,   99,   98,   97,   96,   95,   94,   93,   92,
       91,   90,   89,   88,   87,   86,   85,   84,   83,   82,
       81,   80,   79,   78,   77,   76,   75,   73,   72,   71,
       67,   47,   46,   44,   43,   42,   41,   40,   39,   38,
       37,   36,   35,   34,   33,   32,   31,   30,   29,   28,
       27,   26,   25,   24,   23,   22,   21,   20,   19,   17,
       16,   15,   14,    7,  570,  570,  570,  570,  570,  570,

      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570,  570,  570,  570,  570,  570,  570,
      570,  570,  570,  570
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gedcom_hilo.lex"
#define INITIAL 0
/* Lexer for Unicode encoding (high-low order) of Gedcom.
   Copyright (C) 2001 The Genes Development Team
   This file is part of the Gedcom parser library.
   Contributed by Peter Verthez <Peter.Verthez@advalvas.be>, 2001.

   The Gedcom parser library is free software; you can redistribute it
   and/or modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The Gedcom parser library is distributed in the hope that it will be
   useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the Gedcom parser library; if not, write to the
   Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
   02111-1307 USA.  */
/* $Id: gedcom_hilo.lex,v 1.9 2003/01/27 20:13:58 verthezp Exp $ */
/* $Name: R0_90_0 $ */
/* In high-low order, a space is encoded as 0x00 0x20 */
/* i.e. this is utf-16-be */
#line 28 "gedcom_hilo.lex"
#define LEX_SECTION 1  /* include only a specific part of the following file */
#define yymyinit gedcom_hilo_myinit
#include "gedcom_lex_common.c"
  
static size_t encoding_width = 2;
#define NORMAL 1

#define EXPECT_TAG 2

#line 860 "lex.gedcom_hilo_.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 57 "gedcom_hilo.lex"



#undef LEX_SECTION
#define LEX_SECTION 2  /* include only a specific part of the following file */
#include "gedcom_lex_common.c"

ACTION_BEFORE_REGEXPS
  


#line 1023 "lex.gedcom_hilo_.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 571 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 795 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 68 "gedcom_hilo.lex"
ACTION_INITIAL_WHITESPACE
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 70 "gedcom_hilo.lex"
ACTION_0_DIGITS
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 72 "gedcom_hilo.lex"
ACTION_DIGITS
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 74 "gedcom_hilo.lex"
MKTAGACTION(ABBR)
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 75 "gedcom_hilo.lex"
MKTAGACTION(ADDR)
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 76 "gedcom_hilo.lex"
MKTAGACTION(ADR1)
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 77 "gedcom_hilo.lex"
MKTAGACTION(ADR2)
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 78 "gedcom_hilo.lex"
MKTAGACTION(ADOP)
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 79 "gedcom_hilo.lex"
MKTAGACTION(AFN)
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "gedcom_hilo.lex"
MKTAGACTION(AGE)
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 81 "gedcom_hilo.lex"
MKTAGACTION(AGNC)
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 82 "gedcom_hilo.lex"
MKTAGACTION(ALIA)
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 83 "gedcom_hilo.lex"
MKTAGACTION(ANCE)
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 84 "gedcom_hilo.lex"
MKTAGACTION(ANCI)
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 85 "gedcom_hilo.lex"
MKTAGACTION(ANUL)
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 86 "gedcom_hilo.lex"
MKTAGACTION(ASSO)
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 87 "gedcom_hilo.lex"
MKTAGACTION(AUTH)
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 88 "gedcom_hilo.lex"
MKTAGACTION(BAPL)
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 89 "gedcom_hilo.lex"
MKTAGACTION(BAPM)
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 90 "gedcom_hilo.lex"
MKTAGACTION(BARM)
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 91 "gedcom_hilo.lex"
MKTAGACTION(BASM)
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 92 "gedcom_hilo.lex"
MKTAGACTION(BIRT)
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 93 "gedcom_hilo.lex"
MKTAGACTION(BLES)
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 94 "gedcom_hilo.lex"
MKTAGACTION(BLOB)
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 95 "gedcom_hilo.lex"
MKTAGACTION(BURI)
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 96 "gedcom_hilo.lex"
MKTAGACTION(CALN)
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 97 "gedcom_hilo.lex"
MKTAGACTION(CAST)
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 98 "gedcom_hilo.lex"
MKTAGACTION(CAUS)
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 99 "gedcom_hilo.lex"
MKTAGACTION(CENS)
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 100 "gedcom_hilo.lex"
MKTAGACTION(CHAN)
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 101 "gedcom_hilo.lex"
MKTAGACTION(CHAR)
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 102 "gedcom_hilo.lex"
MKTAGACTION(CHIL)
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 103 "gedcom_hilo.lex"
MKTAGACTION(CHR)
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 104 "gedcom_hilo.lex"
MKTAGACTION(CHRA)
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 105 "gedcom_hilo.lex"
MKTAGACTION(CITY)
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 106 "gedcom_hilo.lex"
MKTAGACTION(CONC)
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 107 "gedcom_hilo.lex"
MKTAGACTION(CONF)
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 108 "gedcom_hilo.lex"
MKTAGACTION(CONL)
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 109 "gedcom_hilo.lex"
MKTAGACTION(CONT)
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 110 "gedcom_hilo.lex"
MKTAGACTION(COPR)
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 111 "gedcom_hilo.lex"
MKTAGACTION(CORP)
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 112 "gedcom_hilo.lex"
MKTAGACTION(CREM)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 113 "gedcom_hilo.lex"
MKTAGACTION(CTRY)
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 114 "gedcom_hilo.lex"
MKTAGACTION(DATA)
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 115 "gedcom_hilo.lex"
MKTAGACTION(DATE)
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 116 "gedcom_hilo.lex"
MKTAGACTION(DEAT)
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 117 "gedcom_hilo.lex"
MKTAGACTION(DESC)
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 118 "gedcom_hilo.lex"
MKTAGACTION(DESI)
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 119 "gedcom_hilo.lex"
MKTAGACTION(DEST)
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 120 "gedcom_hilo.lex"
MKTAGACTION(DIV)
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 121 "gedcom_hilo.lex"
MKTAGACTION(DIVF)
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 122 "gedcom_hilo.lex"
MKTAGACTION(DSCR)
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 123 "gedcom_hilo.lex"
MKTAGACTION(EDUC)
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 124 "gedcom_hilo.lex"
MKTAGACTION(EMIG)
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 125 "gedcom_hilo.lex"
MKTAGACTION(ENDL)
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 126 "gedcom_hilo.lex"
MKTAGACTION(ENGA)
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 127 "gedcom_hilo.lex"
MKTAGACTION(EVEN)
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 128 "gedcom_hilo.lex"
MKTAGACTION(FAM)
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 129 "gedcom_hilo.lex"
MKTAGACTION(FAMC)
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 130 "gedcom_hilo.lex"
MKTAGACTION(FAMF)
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 131 "gedcom_hilo.lex"
MKTAGACTION(FAMS)
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 132 "gedcom_hilo.lex"
MKTAGACTION(FCOM)
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 133 "gedcom_hilo.lex"
MKTAGACTION(FILE)
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 134 "gedcom_hilo.lex"
MKTAGACTION(FORM)
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 135 "gedcom_hilo.lex"
MKTAGACTION(GEDC)
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 136 "gedcom_hilo.lex"
MKTAGACTION(GIVN)
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 137 "gedcom_hilo.lex"
MKTAGACTION(GRAD)
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 138 "gedcom_hilo.lex"
MKTAGACTION(HEAD)
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 139 "gedcom_hilo.lex"
MKTAGACTION(HUSB)
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 140 "gedcom_hilo.lex"
MKTAGACTION(IDNO)
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 141 "gedcom_hilo.lex"
MKTAGACTION(IMMI)
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 142 "gedcom_hilo.lex"
MKTAGACTION(INDI)
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 143 "gedcom_hilo.lex"
MKTAGACTION(LANG)
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 144 "gedcom_hilo.lex"
MKTAGACTION(LEGA)
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 145 "gedcom_hilo.lex"
MKTAGACTION(MARB)
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 146 "gedcom_hilo.lex"
MKTAGACTION(MARC)
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 147 "gedcom_hilo.lex"
MKTAGACTION(MARL)
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 148 "gedcom_hilo.lex"
MKTAGACTION(MARR)
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 149 "gedcom_hilo.lex"
MKTAGACTION(MARS)
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 150 "gedcom_hilo.lex"
MKTAGACTION(MEDI)
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 151 "gedcom_hilo.lex"
MKTAGACTION(NAME)
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 152 "gedcom_hilo.lex"
MKTAGACTION(NATI)
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 153 "gedcom_hilo.lex"
MKTAGACTION(NATU)
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 154 "gedcom_hilo.lex"
MKTAGACTION(NCHI)
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 155 "gedcom_hilo.lex"
MKTAGACTION(NICK)
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 156 "gedcom_hilo.lex"
MKTAGACTION(NMR)
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 157 "gedcom_hilo.lex"
MKTAGACTION(NOTE)
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 158 "gedcom_hilo.lex"
MKTAGACTION(NPFX)
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 159 "gedcom_hilo.lex"
MKTAGACTION(NSFX)
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 160 "gedcom_hilo.lex"
MKTAGACTION(OBJE)
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 161 "gedcom_hilo.lex"
MKTAGACTION(OCCU)
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 162 "gedcom_hilo.lex"
MKTAGACTION(ORDI)
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 163 "gedcom_hilo.lex"
MKTAGACTION(ORDN)
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 164 "gedcom_hilo.lex"
MKTAGACTION(PAGE)
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 165 "gedcom_hilo.lex"
MKTAGACTION(PEDI)
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 166 "gedcom_hilo.lex"
MKTAGACTION(PHON)
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 167 "gedcom_hilo.lex"
MKTAGACTION(PLAC)
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 168 "gedcom_hilo.lex"
MKTAGACTION(POST)
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 169 "gedcom_hilo.lex"
MKTAGACTION(PROB)
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 170 "gedcom_hilo.lex"
MKTAGACTION(PROP)
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 171 "gedcom_hilo.lex"
MKTAGACTION(PUBL)
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 172 "gedcom_hilo.lex"
MKTAGACTION(QUAY)
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 173 "gedcom_hilo.lex"
MKTAGACTION(REFN)
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 174 "gedcom_hilo.lex"
MKTAGACTION(RELA)
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 175 "gedcom_hilo.lex"
MKTAGACTION(RELI)
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 176 "gedcom_hilo.lex"
MKTAGACTION(REPO)
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 177 "gedcom_hilo.lex"
MKTAGACTION(RESI)
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 178 "gedcom_hilo.lex"
MKTAGACTION(RESN)
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 179 "gedcom_hilo.lex"
MKTAGACTION(RETI)
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 180 "gedcom_hilo.lex"
MKTAGACTION(RFN)
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 181 "gedcom_hilo.lex"
MKTAGACTION(RIN)
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 182 "gedcom_hilo.lex"
MKTAGACTION(ROLE)
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 183 "gedcom_hilo.lex"
MKTAGACTION(SEX)
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 184 "gedcom_hilo.lex"
MKTAGACTION(SLGC)
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 185 "gedcom_hilo.lex"
MKTAGACTION(SLGS)
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 186 "gedcom_hilo.lex"
MKTAGACTION(SOUR)
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 187 "gedcom_hilo.lex"
MKTAGACTION(SPFX)
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 188 "gedcom_hilo.lex"
MKTAGACTION(SSN)
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 189 "gedcom_hilo.lex"
MKTAGACTION(STAE)
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 190 "gedcom_hilo.lex"
MKTAGACTION(STAT)
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 191 "gedcom_hilo.lex"
MKTAGACTION(SUBM)
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 192 "gedcom_hilo.lex"
MKTAGACTION(SUBN)
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 193 "gedcom_hilo.lex"
MKTAGACTION(SURN)
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 194 "gedcom_hilo.lex"
MKTAGACTION(TEMP)
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 195 "gedcom_hilo.lex"
MKTAGACTION(TEXT)
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 196 "gedcom_hilo.lex"
MKTAGACTION(TIME)
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 197 "gedcom_hilo.lex"
MKTAGACTION(TITL)
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 198 "gedcom_hilo.lex"
MKTAGACTION(TRLR)
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 199 "gedcom_hilo.lex"
MKTAGACTION(TYPE)
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 200 "gedcom_hilo.lex"
MKTAGACTION(VERS)
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 201 "gedcom_hilo.lex"
MKTAGACTION(WIFE)
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 202 "gedcom_hilo.lex"
MKTAGACTION(WILL)
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 204 "gedcom_hilo.lex"
ACTION_ALPHANUM
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 206 "gedcom_hilo.lex"
ACTION_DELIM
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 208 "gedcom_hilo.lex"
ACTION_ANY
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 210 "gedcom_hilo.lex"
ACTION_ESCAPE
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 212 "gedcom_hilo.lex"
ACTION_POINTER
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 214 "gedcom_hilo.lex"
ACTION_TERMINATOR
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NORMAL):
case YY_STATE_EOF(EXPECT_TAG):
#line 216 "gedcom_hilo.lex"
ACTION_EOF
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 218 "gedcom_hilo.lex"
ACTION_NORMAL_AT
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 220 "gedcom_hilo.lex"
ACTION_TAB
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 222 "gedcom_hilo.lex"
ACTION_UNEXPECTED
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 224 "gedcom_hilo.lex"
ECHO;
	YY_BREAK
#line 1843 "lex.gedcom_hilo_.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 39);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 571 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 39;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 571 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 570);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 224 "gedcom_hilo.lex"

#undef LEX_SECTION
#define LEX_SECTION 3  /* include only a specific part of the following file */
#include "gedcom_lex_common.c"

#ifdef LEXER_TEST
int gedcom_lex()
{
  return gedcom_hilo_lex();
}

int main()
{
  return test_loop(TWO_BYTE_HILO, "UNICODE");
}
#endif
