/* This file is automatically generated */

#define TAG_NUM_START 265
#define TAG_NUM_END   393

char* tag_name[] =
{
  /* 265 */ "ABBR", "ADDR", "ADR1", "ADR2", "ADOP", "AFN", "AGE", "AGNC", 
  /* 273 */ "ALIA", "ANCE", "ANCI", "ANUL", "ASSO", "AUTH", "BAPL", "BAPM", 
  /* 281 */ "BARM", "BASM", "BIRT", "BLES", "BLOB", "BURI", "CALN", "CAST", 
  /* 289 */ "CAUS", "CENS", "CHAN", "CHAR", "CHIL", "CHR", "CHRA", "CITY", 
  /* 297 */ "CONC", "CONF", "CONL", "CONT", "COPR", "CORP", "CREM", "CTRY", 
  /* 305 */ "DATA", "DATE", "DEAT", "DESC", "DESI", "DEST", "DIV", "DIVF", 
  /* 313 */ "DSCR", "EDUC", "EMIG", "ENDL", "ENGA", "EVEN", "FAM", "FAMC", 
  /* 321 */ "FAMF", "FAMS", "FCOM", "FILE", "FORM", "GEDC", "GIVN", "GRAD", 
  /* 329 */ "HEAD", "HUSB", "IDNO", "IMMI", "INDI", "LANG", "LEGA", "MARB", 
  /* 337 */ "MARC", "MARL", "MARR", "MARS", "MEDI", "NAME", "NATI", "NATU", 
  /* 345 */ "NCHI", "NICK", "NMR", "NOTE", "NPFX", "NSFX", "OBJE", "OCCU", 
  /* 353 */ "ORDI", "ORDN", "PAGE", "PEDI", "PHON", "PLAC", "POST", "PROB", 
  /* 361 */ "PROP", "PUBL", "QUAY", "REFN", "RELA", "RELI", "REPO", "RESI", 
  /* 369 */ "RESN", "RETI", "RFN", "RIN", "ROLE", "SEX", "SLGC", "SLGS", 
  /* 377 */ "SOUR", "SPFX", "SSN", "STAE", "STAT", "SUBM", "SUBN", "SURN", 
  /* 385 */ "TEMP", "TEXT", "TIME", "TITL", "TRLR", "TYPE", "VERS", "WIFE", 
  /* 393 */ "WILL", 
};
